import {
  UserProfile,
  Customer,
  Transaction,
  Invoice,
  Product,
  Expense,
  SavingsGoal,
  PaymentReminder,
  DocumentItem,
  SystemSettings
} from '@/types';

export const initialUserProfile: UserProfile = {
  id: 'usr_001',
  name: 'Anant Kumar Yadav',
  email: 'contact@sharmatraders.in',
  phone: '8371838314',
  role: 'business_owner',
  businessName: 'Sharma Traders & Enterprise',
  businessGst: '27AABCS1429B1Z8',
  businessAddress: 'Plot 42, Apex Industrial Park, Andheri East, Mumbai, MH 400069',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  createdAt: '2025-01-10T10:00:00Z',
};

export const initialCustomers: Customer[] = [
  {
    id: 'cust_datta_more',
    name: 'Datta More PUMP ⛽',
    phone: '+91 98220 54321',
    email: 'dattamore.pump@gmail.com',
    businessName: 'Datta Petroleum Fuel Station',
    gstNumber: '27AAMPP8842K1Z9',
    address: 'Near Highway Toll Plaza, Pune - Solapur Rd',
    city: 'Pune',
    state: 'Maharashtra',
    creditLimit: 200000,
    outstandingBalance: 0,
    category: 'Regular',
    status: 'active',
    rating: 5,
    notes: 'Fuel credit ledger account',
    createdAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'cust_01',
    name: 'Amit Verma',
    phone: '+91 98201 11223',
    email: 'amit.verma@apextech.in',
    businessName: 'Apex Tech Solutions',
    gstNumber: '27AAECV1109A1ZT',
    address: '104, Blue Ridge Towers, Hinjewadi',
    city: 'Pune',
    state: 'Maharashtra',
    creditLimit: 150000,
    outstandingBalance: 34500, // owes us
    category: 'VIP',
    status: 'active',
    rating: 5,
    notes: 'Regular prompt payer, preferred client for electronics',
    createdAt: '2025-01-12T09:30:00Z',
  },
  {
    id: 'cust_02',
    name: 'Priya Sundaram',
    phone: '+91 97112 33445',
    email: 'priya@sundaramtextiles.com',
    businessName: 'Sundaram Silk Mills',
    gstNumber: '33AABCS4455G1ZM',
    address: '77 Cotton Market Road',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    creditLimit: 300000,
    outstandingBalance: 82000,
    category: 'Wholesale',
    status: 'overdue',
    rating: 4,
    notes: 'Invoice #1042 due since last week, gentle reminder sent',
    createdAt: '2025-01-15T11:20:00Z',
  },
  {
    id: 'cust_03',
    name: 'Gurpreet Singh',
    phone: '+91 94170 55667',
    email: 'gurpreet@singhhardware.in',
    businessName: 'Singh Hardware & Tools',
    gstNumber: '03AABBS2211C1ZX',
    address: 'Shop 12, GT Road Market',
    city: 'Ludhiana',
    state: 'Punjab',
    creditLimit: 100000,
    outstandingBalance: -15000, // advance received (we owe them goods)
    category: 'Regular',
    status: 'active',
    rating: 5,
    notes: 'Paid 15,000 advance for heavy drill machinery',
    createdAt: '2025-02-01T14:15:00Z',
  },
  {
    id: 'cust_04',
    name: 'Deepak Patel',
    phone: '+91 98980 77889',
    email: 'deepak@patelautomotive.com',
    businessName: 'Patel Auto Spares',
    gstNumber: '24AAACP9988H1ZV',
    address: '22 Ring Road, Sarkhej',
    city: 'Ahmedabad',
    state: 'Gujarat',
    creditLimit: 250000,
    outstandingBalance: 56000,
    category: 'Wholesale',
    status: 'active',
    rating: 4,
    notes: 'Weekly consolidated billing',
    createdAt: '2025-02-10T16:00:00Z',
  },
  {
    id: 'cust_05',
    name: 'Neha Roy',
    phone: '+91 98300 44556',
    email: 'neha.roy@roystationery.in',
    businessName: 'Roy Premium Stationers',
    gstNumber: '19AABCR8877K1ZD',
    address: '5 College Street',
    city: 'Kolkata',
    state: 'West Bengal',
    creditLimit: 50000,
    outstandingBalance: 12500,
    category: 'Retail',
    status: 'active',
    rating: 4,
    notes: 'New client, good payment behavior',
    createdAt: '2025-02-18T10:00:00Z',
  }
];

export const initialTransactions: Transaction[] = [
  {
    id: 'txn_datta_01',
    type: 'credit',
    amount: 4000,
    date: '2026-08-25T17:06:00Z',
    customerId: 'cust_datta_more',
    customerName: 'Datta More PUMP ⛽',
    category: 'Fuel / Goods Given',
    paymentMode: 'other',
    note: 'Sumant Admission Diploma ke liye Liya Tha',
    status: 'completed',
    createdBy: 'Merchant',
    createdAt: '2026-08-25T17:06:00Z',
  },
  {
    id: 'txn_datta_02',
    type: 'debit',
    amount: 4000,
    date: '2026-08-26T09:22:00Z',
    customerId: 'cust_datta_more',
    customerName: 'Datta More PUMP ⛽',
    category: 'UPI Payment',
    paymentMode: 'upi',
    referenceNo: 'AXIS BANK ••4284 via UPI',
    note: 'bhopal jana tha isliye liya',
    status: 'completed',
    createdBy: 'Merchant',
    createdAt: '2026-08-26T09:22:00Z',
  },
  {
    id: 'txn_datta_03',
    type: 'credit',
    amount: 4000,
    date: new Date().toISOString(),
    customerId: 'cust_datta_more',
    customerName: 'Datta More PUMP ⛽',
    category: 'Bank Transfer',
    paymentMode: 'bank_transfer',
    note: 'Payment should now be in SADANAND RAMA BHOIR\'s bank account',
    attachments: [
      JSON.stringify({
        id: 'att_dm_01',
        url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
        name: 'Payment_Success.jpg',
        type: 'image',
        size: '240 KB'
      }),
      JSON.stringify({
        id: 'att_dm_02',
        url: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&auto=format&fit=crop&q=80',
        name: 'Bank_Receipt.jpg',
        type: 'image',
        size: '180 KB'
      })
    ],
    status: 'completed',
    createdBy: 'Merchant',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'txn_001',
    type: 'collection',
    amount: 25000,
    date: '2025-03-01T11:00:00Z',
    customerId: 'cust_01',
    customerName: 'Amit Verma',
    category: 'UPI Collection',
    paymentMode: 'upi',
    referenceNo: 'UPI/5060708090',
    note: 'Payment received via SmartKhata UPI QR',
    status: 'completed',
    createdBy: 'Rajesh Sharma',
    createdAt: '2025-03-01T11:00:00Z',
  },
  {
    id: 'txn_002',
    type: 'credit',
    amount: 34500,
    date: '2025-03-02T15:30:00Z',
    customerId: 'cust_01',
    customerName: 'Amit Verma',
    category: 'Goods Supplied',
    paymentMode: 'cheque',
    note: 'Supplied high-density networking cables & switches',
    status: 'completed',
    createdBy: 'Rajesh Sharma',
    createdAt: '2025-03-02T15:30:00Z',
  },
  {
    id: 'txn_003',
    type: 'expense',
    amount: 14500,
    date: '2025-03-03T10:15:00Z',
    category: 'Office Rent & Maintenance',
    paymentMode: 'bank_transfer',
    referenceNo: 'NEFT-889922001',
    note: 'March Maintenance & Warehouse Electricity Bill',
    status: 'completed',
    createdBy: 'Rajesh Sharma',
    createdAt: '2025-03-03T10:15:00Z',
  },
  {
    id: 'txn_004',
    type: 'income',
    amount: 85000,
    date: '2025-03-04T12:00:00Z',
    customerId: 'cust_04',
    customerName: 'Deepak Patel',
    category: 'Wholesale Sales',
    paymentMode: 'bank_transfer',
    referenceNo: 'IMPS-44332211',
    note: 'Bulk dispatch settlement',
    status: 'completed',
    createdBy: 'Rajesh Sharma',
    createdAt: '2025-03-04T12:00:00Z',
  },
  {
    id: 'txn_005',
    type: 'collection',
    amount: 18000,
    date: '2025-03-05T09:45:00Z',
    customerId: 'cust_02',
    customerName: 'Priya Sundaram',
    category: 'Partial Settlement',
    paymentMode: 'upi',
    referenceNo: 'UPI/9988776655',
    note: 'Partial payment on overdue invoice',
    status: 'completed',
    createdBy: 'Rajesh Sharma',
    createdAt: '2025-03-05T09:45:00Z',
  },
  {
    id: 'txn_006',
    type: 'expense',
    amount: 6200,
    date: '2025-03-06T16:20:00Z',
    category: 'Logistics & Shipping',
    paymentMode: 'upi',
    referenceNo: 'UPI/4455667788',
    note: 'Inter-state courier & transport freight charges',
    status: 'completed',
    createdBy: 'Rajesh Sharma',
    createdAt: '2025-03-06T16:20:00Z',
  }
];

export const initialProducts: Product[] = [
  {
    id: 'prod_01',
    name: 'Industrial CAT6 Cable Drum (305m)',
    sku: 'SKP-CAB-305',
    barcode: '8901234567890',
    category: 'Networking',
    purchasePrice: 4200,
    sellingPrice: 5800,
    currentStock: 48,
    minStock: 15,
    unit: 'boxes',
    supplier: 'Havells India Cable Corp',
    location: 'Aisle 3, Bin 12',
    updatedAt: '2025-03-01T08:00:00Z',
  },
  {
    id: 'prod_02',
    name: 'Gigabit 24-Port Managed Switch',
    sku: 'SKP-SWT-24P',
    barcode: '8901234567891',
    category: 'Networking',
    purchasePrice: 9500,
    sellingPrice: 13500,
    currentStock: 8,
    minStock: 10, // LOW STOCK ALERT
    unit: 'pcs',
    supplier: 'D-Link Enterprise Hub',
    location: 'Aisle 1, Shelf B',
    updatedAt: '2025-03-02T10:00:00Z',
  },
  {
    id: 'prod_03',
    name: 'Heavy Duty Power Inverter 3.5kVA',
    sku: 'SKP-INV-3500',
    barcode: '8901234567892',
    category: 'Power Equipment',
    purchasePrice: 18000,
    sellingPrice: 24500,
    currentStock: 14,
    minStock: 5,
    unit: 'pcs',
    supplier: 'Luminous Power Tech',
    location: 'Warehouse Floor Bay C',
    updatedAt: '2025-03-03T11:30:00Z',
  },
  {
    id: 'prod_04',
    name: 'Thermal Receipt Rolls (Pack of 50)',
    sku: 'SKP-THM-50',
    barcode: '8901234567893',
    category: 'Billing Supplies',
    purchasePrice: 650,
    sellingPrice: 1050,
    currentStock: 5,
    minStock: 20, // LOW STOCK ALERT
    unit: 'boxes',
    supplier: 'PaperCraft Solutions',
    location: 'Aisle 4, Shelf 1',
    updatedAt: '2025-03-04T09:00:00Z',
  },
  {
    id: 'prod_05',
    name: 'Dual-Band WiFi 6 Mesh Router',
    sku: 'SKP-RTR-AX30',
    barcode: '8901234567894',
    category: 'Networking',
    purchasePrice: 3200,
    sellingPrice: 4600,
    currentStock: 32,
    minStock: 8,
    unit: 'pcs',
    supplier: 'TP-Link Systems India',
    location: 'Aisle 2, Bin 4',
    updatedAt: '2025-03-05T14:20:00Z',
  }
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv_1041',
    invoiceNumber: 'SKP/2025/1041',
    type: 'sales',
    customerId: 'cust_01',
    customerName: 'Amit Verma',
    customerPhone: '+91 98201 11223',
    customerGst: '27AAECV1109A1ZT',
    customerAddress: '104, Blue Ridge Towers, Hinjewadi, Pune',
    issueDate: '2025-03-01',
    dueDate: '2025-03-15',
    items: [
      {
        id: 'item_1',
        productId: 'prod_01',
        name: 'Industrial CAT6 Cable Drum (305m)',
        quantity: 5,
        unitPrice: 5800,
        discountPercent: 5,
        taxPercent: 18,
        total: 32509,
      },
      {
        id: 'item_2',
        productId: 'prod_02',
        name: 'Gigabit 24-Port Managed Switch',
        quantity: 2,
        unitPrice: 13500,
        discountPercent: 0,
        taxPercent: 18,
        total: 31860,
      }
    ],
    subtotal: 56000,
    discountAmount: 1450,
    taxAmount: 9819,
    cgst: 4909.5,
    sgst: 4909.5,
    igst: 0,
    total: 64369,
    paidAmount: 64369,
    status: 'paid',
    notes: 'Thank you for your business! Goods once sold cannot be returned without original seal.',
    terms: 'Payment due within 15 days. Interest @ 18% per annum will be charged on overdue bills.',
    createdAt: '2025-03-01T10:00:00Z',
  },
  {
    id: 'inv_1042',
    invoiceNumber: 'SKP/2025/1042',
    type: 'sales',
    customerId: 'cust_02',
    customerName: 'Priya Sundaram',
    customerPhone: '+91 97112 33445',
    customerGst: '33AABCS4455G1ZM',
    customerAddress: '77 Cotton Market Road, Coimbatore',
    issueDate: '2025-02-20',
    dueDate: '2025-03-02',
    items: [
      {
        id: 'item_3',
        productId: 'prod_03',
        name: 'Heavy Duty Power Inverter 3.5kVA',
        quantity: 4,
        unitPrice: 24500,
        discountPercent: 2,
        taxPercent: 18,
        total: 113334,
      }
    ],
    subtotal: 98000,
    discountAmount: 1960,
    taxAmount: 17287.2,
    cgst: 0,
    sgst: 0,
    igst: 17287.2,
    total: 113327,
    paidAmount: 31327,
    status: 'overdue',
    notes: 'Dispatched via SafeXpress Logistic. L/R No: 789123',
    terms: 'Subject to Coimbatore jurisdiction.',
    createdAt: '2025-02-20T11:00:00Z',
  },
  {
    id: 'inv_1043',
    invoiceNumber: 'SKP/2025/1043',
    type: 'sales',
    customerId: 'cust_04',
    customerName: 'Deepak Patel',
    customerPhone: '+91 98980 77889',
    customerGst: '24AAACP9988H1ZV',
    customerAddress: '22 Ring Road, Sarkhej, Ahmedabad',
    issueDate: '2025-03-05',
    dueDate: '2025-03-20',
    items: [
      {
        id: 'item_4',
        productId: 'prod_05',
        name: 'Dual-Band WiFi 6 Mesh Router',
        quantity: 10,
        unitPrice: 4600,
        discountPercent: 4,
        taxPercent: 18,
        total: 52108.8,
      }
    ],
    subtotal: 46000,
    discountAmount: 1840,
    taxAmount: 7948.8,
    cgst: 0,
    sgst: 0,
    igst: 7948.8,
    total: 52108,
    paidAmount: 0,
    status: 'unpaid',
    notes: 'Standard 1-year replacement warranty applicable.',
    createdAt: '2025-03-05T14:00:00Z',
  }
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp_01',
    title: 'Warehouse Rent & Maintenance',
    amount: 32000,
    category: 'Rent',
    date: '2025-03-01',
    paymentMode: 'bank_transfer',
    notes: 'Monthly rental for Apex Logistics Hub Bay 4',
    isRecurring: true,
    recurringFrequency: 'monthly',
    tags: ['fixed', 'essential', 'warehouse'],
    createdAt: '2025-03-01T09:00:00Z',
  },
  {
    id: 'exp_02',
    title: 'Staff Salaries (March Partial)',
    amount: 65000,
    category: 'Salaries',
    date: '2025-03-02',
    paymentMode: 'bank_transfer',
    notes: 'Accountant & 2 Warehouse Associates compensation',
    isRecurring: true,
    recurringFrequency: 'monthly',
    tags: ['payroll', 'employees'],
    createdAt: '2025-03-02T10:00:00Z',
  },
  {
    id: 'exp_03',
    title: 'Delivery Van Fuel & Servicing',
    amount: 4800,
    category: 'Travel & Transport',
    date: '2025-03-04',
    paymentMode: 'upi',
    notes: 'BPCL Petrol Pump fuel fill & oil change',
    isRecurring: false,
    tags: ['vehicle', 'fuel'],
    createdAt: '2025-03-04T12:30:00Z',
  },
  {
    id: 'exp_04',
    title: 'Broadband & High-Speed Optical Fiber',
    amount: 2499,
    category: 'Utilities',
    date: '2025-03-05',
    paymentMode: 'upi',
    notes: 'Airtel Xstream Fiber 300 Mbps commercial connection',
    isRecurring: true,
    recurringFrequency: 'monthly',
    tags: ['internet', 'utility'],
    createdAt: '2025-03-05T11:00:00Z',
  },
  {
    id: 'exp_05',
    title: 'Tea, Coffee & Client Hospitality',
    amount: 1850,
    category: 'Hospitality',
    date: '2025-03-06',
    paymentMode: 'cash',
    notes: 'Snacks & beverages for visiting wholesale distributors',
    isRecurring: false,
    tags: ['office', 'pantry'],
    createdAt: '2025-03-06T15:00:00Z',
  }
];

export const initialSavingsGoals: SavingsGoal[] = [
  {
    id: 'goal_01',
    title: 'Emergency Business Reserve (6 Months)',
    targetAmount: 500000,
    currentAmount: 345000,
    category: 'Emergency Fund',
    deadline: '2025-08-31',
    notes: 'Held in high-yield liquid mutual fund & fixed deposit',
    icon: 'ShieldCheck',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'goal_02',
    title: 'Second Warehouse Expansion Downpayment',
    targetAmount: 1200000,
    currentAmount: 720000,
    category: 'Business Expansion',
    deadline: '2025-12-31',
    notes: 'Lease deposit for Bhiwandi logistics hub',
    icon: 'TrendingUp',
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'goal_03',
    title: 'GST Advance & Annual Tax Reserve',
    targetAmount: 250000,
    currentAmount: 185000,
    category: 'Tax Reserve',
    deadline: '2025-06-30',
    notes: 'Quarterly advance tax buffer',
    icon: 'FileText',
    createdAt: '2025-02-01T00:00:00Z',
  }
];

export const initialReminders: PaymentReminder[] = [
  {
    id: 'rem_01',
    customerId: 'cust_02',
    customerName: 'Priya Sundaram',
    customerPhone: '+91 97112 33445',
    customerEmail: 'priya@sundaramtextiles.com',
    amount: 82000,
    dueDate: '2025-03-02',
    reminderType: 'overdue',
    channels: ['whatsapp', 'sms'],
    status: 'pending',
    messageTemplate: 'Dear Priya Sundaram, a friendly reminder that ₹82,000 against invoice #1042 was due on 02-Mar-2025. Kindly pay via our UPI ID: sharma.traders@okaxis or scan our QR code. Thank you, Sharma Traders.',
  },
  {
    id: 'rem_02',
    customerId: 'cust_04',
    customerName: 'Deepak Patel',
    customerPhone: '+91 98980 77889',
    customerEmail: 'deepak@patelautomotive.com',
    amount: 56000,
    dueDate: '2025-03-20',
    reminderType: 'upcoming',
    channels: ['whatsapp'],
    status: 'scheduled',
    messageTemplate: 'Hello Deepak Patel, your invoice #1043 of ₹52,108 will be due on 20-Mar-2025. Thank you for choosing Sharma Traders.',
  },
  {
    id: 'rem_03',
    customerId: 'cust_05',
    customerName: 'Neha Roy',
    customerPhone: '+91 98300 44556',
    amount: 12500,
    dueDate: '2025-03-10',
    reminderType: 'upcoming',
    channels: ['whatsapp', 'sms'],
    status: 'pending',
    messageTemplate: 'Hello Neha Roy, your balance of ₹12,500 is due on 10-Mar-2025. Tap here to pay via UPI: upi://pay?pa=sharma.traders@okaxis&pn=Sharma+Traders&am=12500',
  }
];

export const initialDocuments: DocumentItem[] = [
  {
    id: 'doc_01',
    title: 'Apex_Warehouse_Lease_Agreement_2025.pdf',
    category: 'contract',
    fileUrl: '/docs/lease_contract.pdf',
    fileType: 'PDF',
    fileSize: '2.4 MB',
    relatedEntityName: 'Apex Industrial Park',
    uploadedAt: '2025-01-10T14:30:00Z',
  },
  {
    id: 'doc_02',
    title: 'GST_Registration_Certificate_SharmaTraders.pdf',
    category: 'tax',
    fileUrl: '/docs/gst_certificate.pdf',
    fileType: 'PDF',
    fileSize: '1.1 MB',
    relatedEntityName: 'Government of India',
    uploadedAt: '2025-01-12T11:00:00Z',
  },
  {
    id: 'doc_03',
    title: 'SafeXpress_Dispatch_Receipt_789123.jpg',
    category: 'receipt',
    fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    fileType: 'JPG',
    fileSize: '840 KB',
    relatedEntityId: 'inv_1042',
    relatedEntityName: 'Priya Sundaram',
    uploadedAt: '2025-02-20T16:45:00Z',
  }
];

export const initialSystemSettings: SystemSettings = {
  backendProvider: 'local',
  mongodbUri: 'mongodb+srv://smartkhata:KhataPass%402026@cluster0.7evxtf6.mongodb.net/?appName=Cluster0',
  mongodbDbName: 'smartkhata_db',
  businessName: 'Sharma Traders & Enterprise',
  businessTagline: 'Track Money, Manage Business, Grow Faster',
  businessPhone: '8371838314',
  businessEmail: 'contact@sharmatraders.in',
  businessAddress: 'Plot 42, Apex Industrial Park, Andheri East, Mumbai, MH 400069',
  paymentSettings: {
    collectionMode: 'direct_upi',
    upiId: '8371838314@upi',
    payeeName: 'Sharma Traders & Enterprise',
    // Realistic default QR code provided out of the box
    customQrUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=upi%3A%2F%2Fpay%3Fpa%3D8371838314%40upi%26pn%3DSharma%2BTraders%26cu%3DINR',
    isDefaultQrSaved: true,
    businessGst: '27AABCS1429B1Z8',
    currency: 'INR',
    enableSoundAlerts: true,
    cashfreeAppId: '',
    cashfreeSecretKey: '',
    cashfreeEnv: 'sandbox',
    razorpayKeyId: '',
    razorpayKeySecret: '',
    razorpayWebhookSecret: '',
    razorpayEnv: 'test',
    upiGatewayProvider: 'Cashfree UPI Gateway',
    upiGatewayKey: '',
    upiGatewaySecret: '',
    upiGatewayWebhookUrl: 'https://api.smartkhatapro.in/webhook/upi-payment',
  },
  darkMode: false,
};
